export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LIKE = 'LIKE';
export const DISLIKE = 'DISLIKE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_MATCHES = 'UPDATE_MATCHES'
export const UPDATE_REQUEST_STATE = 'UPDATE_REQUEST_STATE';
export const UPDATE_ALL_HOBBIES = 'UPDATE_ALL_HOBBIES';
export const UPDATE_USER_HOBBIES = 'UPDATE_USER_HOBBIES';
export const UPDATE_POTENTIAL_MATCHES = "UPDATE_POTENTIAL_MATCHES";

export const PENDING_NEW_REQUEST = 'PENDING_NEW_REQUEST';
export const WAITING = 'WAITING';
export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';